version: '3.6'

services:
  db2:
    container_name: db2
    build:
      context: ./
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    environment:
      - DB2_HOST=${DB2_HOST}
      - DB2_PORT=${DB2_PORT}
      - DB2_DB=${DB2_DB}
      - DB2_PROTOCOL=${DB2_PROTOCOL}
      - DB2_USER=${DB2_USER}
      - DB2_PASSWORD=${DB2_PASSWORD}